### ISSUE TITLE
only voice is working in a single way

### ISSUE THREAD

**Issue by priyankoctal** [opentok/opentok-cordova-samples#16] opened 2018-07-31 12:45 UTC
user which connect later can hear and speak the voice but its not working vice versa

**Comment by msach22** [comment] 2019-02-22 21:11
@priyankoctal Can you please clarify what you're seeing and share some code samples of your application?

**Comment by alaghusun60** [comment] 2019-03-01 08:08
we use same sample basic video chat. cordova to browser working. Sometime in one side other person camera with voice visible. Sometime only others voice visible not camera. android to android didnt work using cordova

**Comment by msach22** [comment] 2019-03-05 17:52
@alaghusun60 looks like you filed a similar issue which was recently resolved: https://github.com/opentok/opentok-cordova-samples/issues/23

I'm going to go ahead and close this issue, please feel free to reopen if the issue still persists.

**Closed by msach22** 2019-03-05 17:52 UTC

**Comment by alaghusun60** [comment] 2019-03-06 07:24
But i didnt see any solution here

**Comment by msach22** [comment] 2019-03-31 18:05
@alaghusun60 I'm not able to reproduce this issue. Could you please share which version of the plugin you're using?
